# Instructions:
# Change or add read names in the samples section below.

# Test data read name is specified.
samples:
    - SRR9984301
    
params:
  trimmomatic:
    adapters: "TruSeq3-PE.fa"
    options: "ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36"
